CREATE TABLE [dbo].[Boletas]
(
	[BoletaId] INT NOT NULL PRIMARY KEY IDENTITY,
	[CodigoBoleta] VARCHAR(10) NOT NULL,
	[NumeroEnvio] VARCHAR(10) NOT NULL DEFAULT '',
	[ProveedorId] INT NOT NULL,
	[PlacaEquipo] VARCHAR(10) NOT NULL DEFAULT '',
	[Motorista] VARCHAR(50) NOT NULL DEFAULT '',
	[CategoriaProductoId] INT NOT NULL,
	[PlantaId] INT NOT NULL,
	[PesoEntrada] DECIMAL(18,2) NOT NULL DEFAULT 0.00,
	[PesoSalida] DECIMAL(18,2) NOT NULL DEFAULT 0.00,
	[PesoProducto] DECIMAL(18,2) NOT NULL,
	[CantidadPenalizada] DECIMAL(18,2) NOT NULL DEFAULT 0.00,
	[Bonus] DECIMAL(18,2) NOT NULL DEFAULT 0.00,
	[PrecioProductoCompra] DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
	[PrecioProductoVenta] DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
	[FechaSalida] DATE NOT NULL DEFAULT GETDATE(),
	[FechaCreacionBoleta] DATE NOT NULL DEFAULT GETDATE(),
	[Estado] VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
	[BoletaPath] VARCHAR(MAX) NOT NULL DEFAULT '', 
	[TipoTransaccion] VARCHAR(50) NOT NULL,
	[DescripcionTransaccion] VARCHAR(50) NOT NULL,
	[ModificadoPor] VARCHAR(15) NOT NULL DEFAULT '',
	[FechaTransaccion] DATETIME NOT NULL DEFAULT GETDATE(),
	[TransaccionUId] uniqueidentifier NOT NULL,
    CONSTRAINT [FK_Boletas_Proveedores] FOREIGN KEY ([ProveedorId]) REFERENCES Proveedores(ProveedorId),
	CONSTRAINT [FK_Boletas_Plantas] FOREIGN KEY ([PlantaId]) REFERENCES ClientePlantas(PlantaId),
	CONSTRAINT [FK_Boletas_CategoriaProductos] FOREIGN KEY ([CategoriaProductoId]) REFERENCES CategoriaProductos(CategoriaProductoId),
)
