CREATE TABLE [dbo].[Facturas_Transacciones]
(
	[UId] INT NOT NULL PRIMARY KEY IDENTITY,
	[FacturaId] INT NOT NULL, 
	[SucursalId] INT NOT NULL,
	[FacturaCategoriaId] INT NOT NULL , 
    [PlantaId] INT NOT NULL,
	[SubPlantaId] INT NULL DEFAULT NULL, 
	[OrdenCompra] VARCHAR(50) NOT NULL DEFAULT '',
	[Semana] VARCHAR(10) NOT NULL DEFAULT '', 
    [TipoFactura] VARCHAR(10) NOT NULL DEFAULT '', 
    [NumeroFactura] VARCHAR(50) NOT NULL DEFAULT '', 
	[ProFormaNo] VARCHAR(10) NOT NULL DEFAULT '', 
    [Fecha] DATE NOT NULL DEFAULT GETDATE(), 
	[IsExonerated] BIT NOT NULL DEFAULT 0, 
	[ExonerationNo] VARCHAR(50) NOT NULL DEFAULT '', 	
    [TaxPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0.00, 
	[Total] DECIMAL(18, 2) NOT NULL DEFAULT 0.00, 
	[IsForeignCurrency] BIT NOT NULL DEFAULT 0, 
    [LocalCurrencyAmount] DECIMAL(18, 2) NOT NULL DEFAULT 0.00, 
    [Observaciones] VARCHAR(MAX) NOT NULL DEFAULT '', 
    [Estado] VARCHAR(10) NOT NULL DEFAULT 'ACTIVO',
	[HasUnitPriceItem] BIT NOT NULL DEFAULT 0, 
	[TipoTransaccion] VARCHAR(50) NOT NULL,
	[DescripcionTransaccion] VARCHAR(50) NOT NULL,
	[ModificadoPor] VARCHAR(15) NOT NULL DEFAULT '',
	[FechaTransaccion] DATETIME NOT NULL DEFAULT GETDATE(),
	[TransaccionUId] uniqueidentifier NOT NULL
)
