//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercialColindres.ReglasNegocio.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyDeducciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyDeducciones() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComercialColindres.ReglasNegocio.Recursos.KeyDeducciones", typeof(KeyDeducciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abono por Boleta.
        /// </summary>
        internal static string AbonoPorBoleta {
            get {
                return ResourceManager.GetString("AbonoPorBoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abono Prestamo.
        /// </summary>
        internal static string AbonoPrestamo {
            get {
                return ResourceManager.GetString("AbonoPrestamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajuste de Boletas.
        /// </summary>
        internal static string AjusteBoletas {
            get {
                return ResourceManager.GetString("AjusteBoletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleta Deduccion Manual.
        /// </summary>
        internal static string BoletaDeduccionManual {
            get {
                return ResourceManager.GetString("BoletaDeduccionManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleta con Humedad.
        /// </summary>
        internal static string BoletaHumedad {
            get {
                return ResourceManager.GetString("BoletaHumedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleta Otras Deducciones.
        /// </summary>
        internal static string BoletaOtrasDeducciones {
            get {
                return ResourceManager.GetString("BoletaOtrasDeducciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boleta Otros Ingresos.
        /// </summary>
        internal static string BoletaOtrosIngresos {
            get {
                return ResourceManager.GetString("BoletaOtrosIngresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descarga de Producto.
        /// </summary>
        internal static string Descargadores {
            get {
                return ResourceManager.GetString("Descargadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden Combustible.
        /// </summary>
        internal static string OrdenCombustible {
            get {
                return ResourceManager.GetString("OrdenCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestamo Efectivo.
        /// </summary>
        internal static string PrestamoEfectivo {
            get {
                return ResourceManager.GetString("PrestamoEfectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa Seguridad.
        /// </summary>
        internal static string TasaSeguridad {
            get {
                return ResourceManager.GetString("TasaSeguridad", resourceCulture);
            }
        }
    }
}
