//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercialColindres.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Estados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Estados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComercialColindres.Recursos.Estados", typeof(Estados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVO.
        /// </summary>
        internal static string ACTIVO {
            get {
                return ResourceManager.GetString("ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANULADO.
        /// </summary>
        internal static string ANULADO {
            get {
                return ResourceManager.GetString("ANULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CERRADO.
        /// </summary>
        internal static string CERRADO {
            get {
                return ResourceManager.GetString("CERRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENPROCESO.
        /// </summary>
        internal static string ENPROCESO {
            get {
                return ResourceManager.GetString("ENPROCESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTRANSITO.
        /// </summary>
        internal static string ENTRANSITO {
            get {
                return ResourceManager.GetString("ENTRANSITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INACTIVO.
        /// </summary>
        internal static string INACTIVO {
            get {
                return ResourceManager.GetString("INACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVENTARIO.
        /// </summary>
        internal static string INVENTARIO {
            get {
                return ResourceManager.GetString("INVENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIBERADO.
        /// </summary>
        internal static string LIBERADO {
            get {
                return ResourceManager.GetString("LIBERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUEVO.
        /// </summary>
        internal static string NUEVO {
            get {
                return ResourceManager.GetString("NUEVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDIENTE.
        /// </summary>
        internal static string PENDIENTE {
            get {
                return ResourceManager.GetString("PENDIENTE", resourceCulture);
            }
        }
    }
}
