//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercialColindres.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComercialColindres.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está Seguro de querer Activar la Boleta {0}?.
        /// </summary>
        internal static string Abrir_Boleta {
            get {
                return ResourceManager.GetString("Abrir_Boleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Activar la Linea de Crédito {0}?.
        /// </summary>
        internal static string Activando_LineaCredito {
            get {
                return ResourceManager.GetString("Activando_LineaCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Activar la PO {0} de BIOMASA para la Planta {1}?.
        /// </summary>
        internal static string Activando_PO {
            get {
                return ResourceManager.GetString("Activando_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Activar el Ajuste para la Boleta #{0}?.
        /// </summary>
        internal static string Activar_AjusteBoleta {
            get {
                return ResourceManager.GetString("Activar_AjusteBoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Activar la Factura # {0}?.
        /// </summary>
        internal static string Activar_Factura {
            get {
                return ResourceManager.GetString("Activar_Factura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Actualizar los Datos {0}?.
        /// </summary>
        internal static string Actualizando_Datos {
            get {
                return ResourceManager.GetString("Actualizando_Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Anular el Registro {0}?.
        /// </summary>
        internal static string Anular_Datos {
            get {
                return ResourceManager.GetString("Anular_Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea Cerrar la PO {0} de BIOMASA para la Planta {1}?.
        /// </summary>
        internal static string Cerrando_PO {
            get {
                return ResourceManager.GetString("Cerrando_PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Cerrar la Boleta {0}?.
        /// </summary>
        internal static string Cerrar_Boleta {
            get {
                return ResourceManager.GetString("Cerrar_Boleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Actualizados satisfactoriamente.
        /// </summary>
        internal static string Datos_Actualizados {
            get {
                return ResourceManager.GetString("Datos_Actualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos eliminados satisfactoriamente.
        /// </summary>
        internal static string Datos_Eliminados {
            get {
                return ResourceManager.GetString("Datos_Eliminados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos guardados satisfactoriamente.
        /// </summary>
        internal static string Datos_Guardados {
            get {
                return ResourceManager.GetString("Datos_Guardados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea Eliminar el Número de Envío {0} con Humedad para la Planta {1}?.
        /// </summary>
        internal static string Eliminando_BoletaHumedad {
            get {
                return ResourceManager.GetString("Eliminando_BoletaHumedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está Seguro de querer Eliminar la Boleta {0}?.
        /// </summary>
        internal static string Eliminando_Boletas {
            get {
                return ResourceManager.GetString("Eliminando_Boletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea Eliminar el Registro {0}?.
        /// </summary>
        internal static string Eliminando_Datos {
            get {
                return ResourceManager.GetString("Eliminando_Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea Eliminar la PO {0} de BIOMASA para la Planta {1}?.
        /// </summary>
        internal static string Eliminando_PO {
            get {
                return ResourceManager.GetString("Eliminando_PO", resourceCulture);
            }
        }
    }
}
