//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComercialColindres.Servicios.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyCache {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyCache() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComercialColindres.Servicios.Recursos.KeyCache", typeof(KeyCache).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AjusteBoletaDetalles.
        /// </summary>
        internal static string AjusteBoletaDetalles {
            get {
                return ResourceManager.GetString("AjusteBoletaDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AjusteBoletaPagos.
        /// </summary>
        internal static string AjusteBoletaPagos {
            get {
                return ResourceManager.GetString("AjusteBoletaPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AjusteBoletas.
        /// </summary>
        internal static string AjusteBoletas {
            get {
                return ResourceManager.GetString("AjusteBoletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AjusteTipos.
        /// </summary>
        internal static string AjusteTipos {
            get {
                return ResourceManager.GetString("AjusteTipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bancos.
        /// </summary>
        internal static string Bancos {
            get {
                return ResourceManager.GetString("Bancos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoletaDeduccionesManual.
        /// </summary>
        internal static string BoletaDeduccionesManual {
            get {
                return ResourceManager.GetString("BoletaDeduccionesManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoletaOtrasDeducciones.
        /// </summary>
        internal static string BoletaOtrasDeducciones {
            get {
                return ResourceManager.GetString("BoletaOtrasDeducciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boletas.
        /// </summary>
        internal static string Boletas {
            get {
                return ResourceManager.GetString("Boletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoletasCierres.
        /// </summary>
        internal static string BoletasCierres {
            get {
                return ResourceManager.GetString("BoletasCierres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoletasDetalles.
        /// </summary>
        internal static string BoletasDetalles {
            get {
                return ResourceManager.GetString("BoletasDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoletasHumedad.
        /// </summary>
        internal static string BoletasHumedad {
            get {
                return ResourceManager.GetString("BoletasHumedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoletasHumedadAsignacion.
        /// </summary>
        internal static string BoletasHumedadAsignacion {
            get {
                return ResourceManager.GetString("BoletasHumedadAsignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoletasHumedadPago.
        /// </summary>
        internal static string BoletasHumedadPago {
            get {
                return ResourceManager.GetString("BoletasHumedadPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonificacionProducto.
        /// </summary>
        internal static string BonificacionProducto {
            get {
                return ResourceManager.GetString("BonificacionProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoriaProductos.
        /// </summary>
        internal static string CategoriaProductos {
            get {
                return ResourceManager.GetString("CategoriaProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string Clientes {
            get {
                return ResourceManager.GetString("Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conductores.
        /// </summary>
        internal static string Conductores {
            get {
                return ResourceManager.GetString("Conductores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlativos.
        /// </summary>
        internal static string Correlativos {
            get {
                return ResourceManager.GetString("Correlativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrillas.
        /// </summary>
        internal static string Cuadrillas {
            get {
                return ResourceManager.GetString("Cuadrillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CuentasBancarias.
        /// </summary>
        internal static string CuentasBancarias {
            get {
                return ResourceManager.GetString("CuentasBancarias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CuentasFinancieras.
        /// </summary>
        internal static string CuentasFinancieras {
            get {
                return ResourceManager.GetString("CuentasFinancieras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CuentasPorCobrar.
        /// </summary>
        internal static string CuentasPorCobrar {
            get {
                return ResourceManager.GetString("CuentasPorCobrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargadores.
        /// </summary>
        internal static string Descargadores {
            get {
                return ResourceManager.GetString("Descargadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescargasPorAdelantado.
        /// </summary>
        internal static string DescargasPorAdelantado {
            get {
                return ResourceManager.GetString("DescargasPorAdelantado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string Empleados {
            get {
                return ResourceManager.GetString("Empleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipos.
        /// </summary>
        internal static string Equipos {
            get {
                return ResourceManager.GetString("Equipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquiposCategorias.
        /// </summary>
        internal static string EquiposCategorias {
            get {
                return ResourceManager.GetString("EquiposCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacturaDetalleBoletas.
        /// </summary>
        internal static string FacturaDetalleBoletas {
            get {
                return ResourceManager.GetString("FacturaDetalleBoletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacturaDetalleItems.
        /// </summary>
        internal static string FacturaDetalleItems {
            get {
                return ResourceManager.GetString("FacturaDetalleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacturaPago.
        /// </summary>
        internal static string FacturaPago {
            get {
                return ResourceManager.GetString("FacturaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas.
        /// </summary>
        internal static string Facturas {
            get {
                return ResourceManager.GetString("Facturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacturasCategorias.
        /// </summary>
        internal static string FacturasCategorias {
            get {
                return ResourceManager.GetString("FacturasCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuelOrderManualPayments.
        /// </summary>
        internal static string FuelOrderManualPayments {
            get {
                return ResourceManager.GetString("FuelOrderManualPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasCreditoPagos.
        /// </summary>
        internal static string GasCreditoPagos {
            get {
                return ResourceManager.GetString("GasCreditoPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasCreditos.
        /// </summary>
        internal static string GasCreditos {
            get {
                return ResourceManager.GetString("GasCreditos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gasolineras.
        /// </summary>
        internal static string Gasolineras {
            get {
                return ResourceManager.GetString("Gasolineras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineasCredito.
        /// </summary>
        internal static string LineasCredito {
            get {
                return ResourceManager.GetString("LineasCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineasCreditoDeducciones.
        /// </summary>
        internal static string LineasCreditoDeducciones {
            get {
                return ResourceManager.GetString("LineasCreditoDeducciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotasCredito.
        /// </summary>
        internal static string NotasCredito {
            get {
                return ResourceManager.GetString("NotasCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpcionesSistema.
        /// </summary>
        internal static string OpcionesSistema {
            get {
                return ResourceManager.GetString("OpcionesSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdenesCombustible.
        /// </summary>
        internal static string OrdenesCombustible {
            get {
                return ResourceManager.GetString("OrdenesCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdenescompraDetalleBoleta.
        /// </summary>
        internal static string OrdenescompraDetalleBoleta {
            get {
                return ResourceManager.GetString("OrdenescompraDetalleBoleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdenescompraProducto.
        /// </summary>
        internal static string OrdenescompraProducto {
            get {
                return ResourceManager.GetString("OrdenescompraProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdenescompraProductoDetalle.
        /// </summary>
        internal static string OrdenescompraProductoDetalle {
            get {
                return ResourceManager.GetString("OrdenescompraProductoDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagoDescargas.
        /// </summary>
        internal static string PagoDescargas {
            get {
                return ResourceManager.GetString("PagoDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagoDescargasDetalle.
        /// </summary>
        internal static string PagoDescargasDetalle {
            get {
                return ResourceManager.GetString("PagoDescargasDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagoPrestamos.
        /// </summary>
        internal static string PagoPrestamos {
            get {
                return ResourceManager.GetString("PagoPrestamos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrecioDescargas.
        /// </summary>
        internal static string PrecioDescargas {
            get {
                return ResourceManager.GetString("PrecioDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrecioProductos.
        /// </summary>
        internal static string PrecioProductos {
            get {
                return ResourceManager.GetString("PrecioProductos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestamos.
        /// </summary>
        internal static string Prestamos {
            get {
                return ResourceManager.GetString("Prestamos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrestamosTransferencias.
        /// </summary>
        internal static string PrestamosTransferencias {
            get {
                return ResourceManager.GetString("PrestamosTransferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string Proveedores {
            get {
                return ResourceManager.GetString("Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibos.
        /// </summary>
        internal static string Recibos {
            get {
                return ResourceManager.GetString("Recibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubPlantas.
        /// </summary>
        internal static string SubPlantas {
            get {
                return ResourceManager.GetString("SubPlantas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Usuarios {
            get {
                return ResourceManager.GetString("Usuarios", resourceCulture);
            }
        }
    }
}
